kind: Service
apiVersion: v1
metadata:
  name: test-pod-service
  namespace: default
spec:
  selector:
    app: test-deployment
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80