apiVersion: v1
kind: Pod
metadata:
  name: just-a-pod
spec:
  containers:
  - image: mcr.microsoft.com/azure-functions/dotnet:3.0
    name: http
    ports:
    - containerPort: 80
    env:
      - name: MY_ENV
        value: Value2