apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blog-user-role
rules:
  - apiGroups: [ "wordpress.presslabs.org/v1alpha1" ]
    resources:
      - Wordpress
    verbs: [ "get", "list", "watch" ]

